# Generated by Django 2.2 on 2019-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='name',
            field=models.CharField(default='this is not you', max_length=255),
            preserve_default=False,
        ),
    ]
